<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-Q18VUQ5U" name="tests.HomeTest" tests="2" failures="1" timestamp="11 Mar 2020 10:28:35 GMT" time="31.186" errors="0">
  <testcase name="ui_verification" time="24.400" classname="tests.HomeTest"/>
  <testcase name="tiles_count_verification_UI" time="6.786" classname="tests.HomeTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	total_call_count_from_ui is not matching with db expected [true] but found [false],
	answered_calls_count_from_ui is not matching with db expected [true] but found [false],
	AVG CALL DURATION from ui is not matching with db expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	total_call_count_from_ui is not matching with db expected [true] but found [false],
	answered_calls_count_from_ui is not matching with db expected [true] but found [false],
	AVG CALL DURATION from ui is not matching with db expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at pom.HomePage.tilesCount(HomePage.java:468)
	at tests.HomeTest.tiles_count_verification_UI(HomeTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- tiles_count_verification_UI -->
</testsuite> <!-- tests.HomeTest -->
